### ISSUE TITLE
实体中找不到格力设备

### ISSUE THREAD

**Issue by googooog** [xcy1231/Ha-GreeCentralClimate#4]
大佬 按照你的教程添加后找不到格力的设备
在温控器里面只有我米家的浴霸，找不到其他的设备，已经在格力+中更改设备名称了，还是不显示。

日志：
Logger: homeassistant.loader
Source: loader.py:783
First occurred: 下午4:35:53 (1 occurrences)
Last logged: 下午4:35:53

You are using a custom integration gree2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by aprils4** [comment]
我的也是这个情况，可能是因为我的 HA v2021.4.6 版本太高了吧。。报错如下
2021-04-23 08:31:07 ERROR (MainThread) [homeassistant.components.gree.bridge] Unexpected error fetching gree-格力空调 data: 'pack'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/gree/bridge.py", line 38, in _async_update_data
    await self.device.update_state()
  File "/usr/local/lib/python3.8/site-packages/greeclimate/device.py", line 216, in update_state
    self._properties = await network.request_state(
  File "/usr/local/lib/python3.8/site-packages/greeclimate/network.py", line 359, in request_state
    cols = r["pack"]["cols"]
KeyError: 'pack'

**Comment by aprils4** [comment]
希望能被看到ಥ_ಥ

`2021-06-26 21:18:07 INFO (MainThread) [custom_components.gree2.climate] Setting up Gree climate platform
2021-06-26 21:18:07 INFO (MainThread) [custom_components.gree2.climate] scan_broadcast
2021-06-26 21:18:07 INFO (MainThread) [custom_components.gree2.climate] socket send data {'t': 'scan'} to <broadcast>
2021-06-26 21:18:07 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"pack","i":1,"uid":0,"cid":"","tcid":"","pack":"LP24Ek0OaYogxs3iQLjL4BVQrnhhm6bIbF4lYMZHEBXLzN9Hu47j/i2SOavdy6LSJe9nJOSQSkTAceSmRpiXiowZmq4OCIxjplTPagTWdLHakI8L01ztFMDGEJqbVpG5HwVwXwkfxAVGlFCSKfxY2aRXNYcGXOKIKxj2Bw09PDT7uCcQL+2Znh8GznBiMsyyEIKj4lXhPYADBPEHeNEvAPABS1sQ/8wyY9Pa89Li2VA="}
2021-06-26 21:18:07 INFO (Thread-3) [custom_components.gree2.climate] Server received pack {'t': 'dev', 'cid': '', 'bc': '', 'brand': '', 'catalog': '', 'mac': 'b4430da95a00', 'mid': '60', 'model': '', 'name': '格力空调', 'lock': 0, 'series': '', 'vender': '', 'ver': '', 'subCnt': 3}
2021-06-26 21:18:07 INFO (Thread-3) [custom_components.gree2.climate] socket send pack {'mac': 'b4430da95a00', 't': 'bind', 'uid': 0} to 192.168.0.229
2021-06-26 21:18:07 INFO (Thread-3) [custom_components.gree2.climate] socket send data {'cid': 'app', 'i': 1, 't': 'pack', 'uid': 0, 'pack': 'WX2zMOQ9VNo93OkSxOe04WkQCPM+WSN4KzqGRa1xWVSj9mrs/0p7GUTdWxmNaBUt'} to 192.168.0.229
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"pack","i":1,"uid":0,"cid":"","tcid":"app","pack":"FtZAY6UHKBwtaI55He0IndbigvnBprnXzJ0aHiL7qKq+QH04jfHnUKNR2hyCVcB22y3zrzILbeKoX2wwWuzbaSOLwdIa+xnWATQ86PplXU4="}
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Server received pack {'r': 200, 't': 'bindOk', 'mac': 'b4430da95a00', 'key': 'nUw073BY0Sdc1Xe9'}
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] socket send pack {'t': 'subDev', 'mac': 'b4430da95a00', 'i': 0} to 192.168.0.229
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] socket send data {'cid': 'app', 'i': 0, 't': 'pack', 'uid': 0, 'pack': '9CIThUzntiQTfdu+4brA6ySrnvH1nESFzPopxh/VxWHvm5hGd2LiviEPOThwFigS'} to 192.168.0.229
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"pack","i":0,"uid":0,"cid":"","tcid":"app","pack":"WUUF2YiokFZuPd5K2BDZbWqppdgkmyDox1Cht0X2nBF2RA1pL2kPxia/9AAo+ju76+uGlxH63cLuk0IM03IWzS9Os/rjUHolw+KNmFaVxmL0rIwllSpUMq420J2K+j8854AgaUTON5bnZ4XGGikmI5cYfBPsbjo7RqZQ7nWR/c2kTsNMv1Es8YNJlEmjJ3geL06z+uNQeiXD4o2YVpXGYvSsjCWVKlQyrjbQnYr6PzzngCBpRM43ludnhcYaKSYjZJApSNp7rTpkZMRwKD3lvQPmxkbB+f0A/xldzsZRAk0vTrP641B6JcPijZhWlcZiOC+bEQYAM4spchS7dwiZx+eAIGlEzjeW52eFxhopJiMeaYitm19QyFQ1XKkMQd2w"}
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Server received pack {'t': 'subList', 'c': 3, 'i': 0, 'list': [{'mac': '5b9c251b000000', 'name': '格力空调', 'mid': '6092', 'model': '', 'lock': 0}, {'mac': 'bc3d681c000000', 'name': '格力空调', 'mid': '6092', 'model': '', 'lock': 0}, {'mac': '5fc1751a000000', 'name': '格力空调', 'mid': '6041', 'model': '', 'lock': 0}], 'r': 200}
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Scan Gree climate device list: [{'mac': '5b9c251b000000', 'name': '格力空调', 'mid': '6092', 'model': '', 'lock': 0}, {'mac': 'bc3d681c000000', 'name': '格力空调', 'mid': '6092', 'model': '', 'lock': 0}, {'mac': '5fc1751a000000', 'name': '格力空调', 'mid': '6041', 'model': '', 'lock': 0}]
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Initialize the GREE climate device
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Initialize the GREE climate device
2021-06-26 21:18:08 INFO (Thread-3) [custom_components.gree2.climate] Initialize the GREE climate device
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] Gree climate device added to hass()
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send pack {'cols': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'SwingLfRig', 'Quiet', 'SvSt'], 'mac': '5b9c251b000000', 't': 'status'} to 192.168.0.229
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send data {'cid': 'app', 'i': 0, 't': 'pack', 'uid': 0, 'pack': 'QzhAR/dN/lwgQtg/wN8nNo4Vz/eYkfJN1or55AMlYNC5yU8g39onDx5Uw4NnuZD8D32O9ZF9lKyqqAobACYgIFMxLnOVefuiGd5HMB2/NHcQwIi65AjD5eDjxoqUrEDtUU0pffep3xW6YgCL6htJY+DqIITxmelAMI/wcyWmTPjQodRJjyPYfZWNurRSRKRR'} to 192.168.0.229
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] Gree climate device added to hass()
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send pack {'cols': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'SwingLfRig', 'Quiet', 'SvSt'], 'mac': 'bc3d681c000000', 't': 'status'} to 192.168.0.229
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send data {'cid': 'app', 'i': 0, 't': 'pack', 'uid': 0, 'pack': 'QzhAR/dN/lwgQtg/wN8nNo4Vz/eYkfJN1or55AMlYNC5yU8g39onDx5Uw4NnuZD8D32O9ZF9lKyqqAobACYgIFMxLnOVefuiGd5HMB2/NHcQwIi65AjD5eDjxoqUrEDt2xLlLTUjr+TBWpyHwzd5iODqIITxmelAMI/wcyWmTPjQodRJjyPYfZWNurRSRKRR'} to 192.168.0.229
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] Gree climate device added to hass()
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send pack {'cols': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'SwingLfRig', 'Quiet', 'SvSt'], 'mac': '5fc1751a000000', 't': 'status'} to 192.168.0.229
2021-06-26 21:18:08 INFO (MainThread) [custom_components.gree2.climate] socket send data {'cid': 'app', 'i': 0, 't': 'pack', 'uid': 0, 'pack': 'QzhAR/dN/lwgQtg/wN8nNo4Vz/eYkfJN1or55AMlYNC5yU8g39onDx5Uw4NnuZD8D32O9ZF9lKyqqAobACYgIFMxLnOVefuiGd5HMB2/NHcQwIi65AjD5eDjxoqUrEDtOL4sZ3jU16+vnfgDMBN/O+DqIITxmelAMI/wcyWmTPjQodRJjyPYfZWNurRSRKRR'} to 192.168.0.229
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"pack","i":0,"uid":0,"cid":"","tcid":"app","pack":"8LmrtQ9QVDamidJ6tBvKvgRr3PsrkDlKmjD31L27MCAIzsU6l/ahu5yVrrj1aSzspcCrfk47/DwW/wobphjdigeoCz581huZLWcMJ7ZdzOFZ7Po8e54DtPdPLX4xy5DNVYzJPnmIoSYQhPbWCGb8adwaA44ovuyP6bCF+HP7rqtB1RJpPZ5063R3qbTfJqYKhmxLNQQdoX/mKR0zwNJyQGIi972Ign3eOgeMRXC9mXbjjOvPeuHlIMtUgWox9MoN"}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] Server received pack {'t': 'dat', 'r': 200, 'uid': 0, 'cid': 'app', 'mac': '5b9c251b000000', 'cols': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'SwingLfRig', 'Quiet', 'SvSt'], 'dat': [0, 1, 27, 1, 0, 0, 0, 0, 0, 0, 0]}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] Climate 格力空调5b9c251b000000 status: {'Pow': 0, 'Mod': 1, 'WdSpd': 1, 'SetTem': 27, 'Air': 0, 'Blo': 0, 'Health': 0, 'SwhSlp': 0, 'SwingLfRig': 0, 'Quiet': 0, 'SvSt': 0}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调5b9c251b000000 HA target temp set according to HVAC state to: 27
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调5b9c251b000000 HA operation mode set according to HVAC state to: off
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调5b9c251b000000 HA fan mode set according to HVAC state to: low
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"pack","i":0,"uid":0,"cid":"","tcid":"app","pack":"8LmrtQ9QVDamidJ6tBvKvgRr3PsrkDlKmjD31L27MCAymNU/9L+uVvpZm93bzjYnpYZwm7ebMZRK2EIkHz3+zQeoCz581huZLWcMJ7ZdzOFZ7Po8e54DtPdPLX4xy5DNVYzJPnmIoSYQhPbWCGb8adwaA44ovuyP6bCF+HP7rqtB1RJpPZ5063R3qbTfJqYKhmxLNQQdoX/mKR0zwNJyQPIN8O/Hd6RF/vRlcMuvMmjjjOvPeuHlIMtUgWox9MoN"}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] Server received pack {'t': 'dat', 'r': 200, 'uid': 0, 'cid': 'app', 'mac': 'bc3d681c000000', 'cols': ['Pow', 'Mod', 'SetTem', 'WdSpd', 'Air', 'Blo', 'Health', 'SwhSlp', 'SwingLfRig', 'Quiet', 'SvSt'], 'dat': [0, 1, 26, 1, 0, 0, 0, 0, 0, 0, 0]}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] Climate 格力空调bc3d681c000000 status: {'Pow': 0, 'Mod': 1, 'WdSpd': 1, 'SetTem': 26, 'Air': 0, 'Blo': 0, 'Health': 0, 'SwhSlp': 0, 'SwingLfRig': 0, 'Quiet': 0, 'SvSt': 0}
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调bc3d681c000000 HA target temp set according to HVAC state to: 26
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调bc3d681c000000 HA operation mode set according to HVAC state to: off
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] 格力空调bc3d681c000000 HA fan mode set according to HVAC state to: low
2021-06-26 21:18:09 INFO (Thread-3) [custom_components.gree2.climate] socket received from ('192.168.0.229', 7000):{"t":"ret","r":400}`

**Comment by aprils4** [comment]
在看完大神所有帖子和读完日志之后，突然想明白了，在overview里直接添加卡片，搜索“climate”找到了实体！激动不已。。

**Comment by cnzd** [comment]
> 在看完大神所有帖子和读完日志之后，突然想明白了，在overview里直接添加卡片，搜索“climate”找到了实体！激动不已。。

请问你是一代云控还是二代云控

**Comment by xcy1231** [comment]
> 大佬 按照你的教程添加后找不到格力的设备
> 在温控器里面只有我米家的浴霸，找不到其他的设备，已经在格力+中更改设备名称了，还是不显示。
> 
> 日志：
> Logger: homeassistant.loader
> Source: loader.py:783
> First occurred: 下午4:35:53 (1 occurrences)
> Last logged: 下午4:35:53
> 
> You are using a custom integration gree2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

这个日志看起来没什么问题啊，开启debug日志的话应该可以拿到更多的信息的

**Comment by xcy1231** [comment]
原来已经找到了

**Comment by akakoori** [comment]
仓主是否可以考虑参考一下 [@qiaoqiao](https://github.com/qiaoqiao1235/Ha-GreeCentralClimate/blob/4ce4deaabf8716ad5e2e312d4a650538c681198e/custom_components/greeCentral/climate.py#L278) 这位老哥的代码，自动生成实体，另外支持一下HACS？

**Comment by xcy1231** [comment]
> 

这两个简单的支持了下，自定义温度传感器这个之前没明白啥意思，后面考虑考虑

**Comment by akakoori** [comment]
> 这两个简单的支持了下，自定义温度传感器这个之前没明白啥意思，后面考虑考虑
按我的理解，应该是有一些人觉得空调自带的温度传感器不准确或者不好用，想用另外的温度传感器（比如室外的）代替之，但是又不想HA面板上出现两个温度，所以就想整合到一起，实现HA面板上的空调实体的温度显示的是另外的温度传感器的温度

这应该是很小一部分人的需求了

**Comment by xcy1231** [comment]
> > 这两个简单的支持了下，自定义温度传感器这个之前没明白啥意思，后面考虑考虑
> 
> 按我的理解，应该是有一些人觉得空调自带的温度传感器不准确或者不好用，想用另外的温度传感器（比如室外的）代替之，但是又不想HA面板上出现两个温度，所以就想整合到一起，实现HA面板上的空调实体的温度显示的是另外的温度传感器的温度
> 
> 这应该是很小一部分人的需求了

我也是这么想的，但是个人觉得没啥意义，就看一眼，还没有放在外面的信息丰富
