### ISSUE TITLE
正确配置后，不出现climate实体，使用旧版本解决

### ISSUE THREAD

**Issue by git-atlanta** [xcy1231/Ha-GreeCentralClimate#49]
环境：
PVE虚拟机Home Assistant
Core 2024.7.3
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240710.0

报错的版本：240726最新版本

错误表型：无法搜索到climate实体

日志错误：
Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 997, in _async_write_ha_state_from_call_soon_threadsafe
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity GREE Climate_1eb95f1b000000

修正方法：
安装旧版本
https://github.com/xcy1231/Ha-GreeCentralClimate/tree/57f03485c8557f05db43f7752daaaa2a3c35f699
目前climate实体正常工作

configuration.yaml对修正无影响，未使用fake_server，配置如下
climate:
  - platform: gree2
    host: 192.168.3.45
    temp_step: 0.5
    scan_interval: 20

**Comment by scythk** [comment]
出现了同样的问题，格力一代云控，回退到您说的版本后解决
